[package]

name = "snooper"
version = "0.0.1"
authors = [ "Brian Mooney <brian_satchwannabe@hotmail.com>" ]

[[bin]]

name = "snooper"

[dependencies]

docopt = "0.6"
rustc-serialize = "0.3"